org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true


# --- ¡LÍNEA AÑADIDA PARA ARREGLAR EL ERROR 'major version 69'! ---
# Esta línea le dice a Gradle que use la versión de Java (JDK/JBR)
# que viene incluida con Android Studio.
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr